cmd: Remove unused variable `cur` in CompletionHelper()
The `cur` pointer is set but not used in CompletionHelper(). Remove it
to fix a 'set but not used' compiler error when building with
--enable-checking.

cmd.c: In function 'CompletionHelper':
cmd.c:830:21: error: variable 'cur' set but not used [-Werror=unused-but-set-variable]
  830 |         const char *cur = NULL;

Change-Id: Ia2288394d8fe58f9134f01dc33d5e3624cf380ef